name: MacOS
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  macos:
    name: MacOS Release (${{ matrix.osx_build_arch }})
    runs-on: macos-latest
    strategy:
      matrix:
        # Add commits/tags to build against other DuckDB versions
        duckdb_version: [ '<submodule_version>' ]
        vcpkg_version: [ '2023.04.15' ]
        osx_build_arch: [ 'x86_64', 'arm64']
    env:
      OSX_BUILD_ARCH: ${{ matrix.osx_build_arch }}
      GEN: Ninja

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Ninja
        run: brew install ninja

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}-${{ matrix.duckdb_version }}
          save: ${{ github.ref == 'refs/heads/master' || github.repository != 'duckdb/duckdb' }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Build extension
        shell: bash
        run: |
          make release

      - name: Test Extension
        if: ${{ matrix.osx_build_arch == 'x86_64'}}
        shell: bash
        run: |
          ./build/release/test/unittest "*test/postgres_scanner/aws-rds.test"

      - uses: actions/upload-artifact@v2
        with:
          name: osx-${{ matrix.osx_build_arch }}-extension
          path: |
            build/release/extension/postgres_scanner/postgres_scanner.duckdb_extension