on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: centos:7

    steps:

    - name: Install
      run: |
        yum install -y gcc gcc-c++ make python3 postgresql-server

    - name: Install more
      run: |
        yum -y install centos-release-scl-rh 
        yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        ls /usr/pgsql*
        pg_config
        postgresql-setup initdb
        systemctl start postgresql

    - name: Install even more
      run: |
        curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
        python3 get-pip.py --user
        python3 -m pip install awscli cmake --upgrade --user

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update DuckDB submodule
      run: |
        git submodule init
        git submodule update --remote --merge

    - name: Build
      run: |
        export PATH=/github/home/.local/bin:/usr/pgsql-9.2/bin:$PATH
        make release

    - name: Make test databases
      run: |
        ./create-postgres-tables.sh

    - name: Test
      run: |
        ./duckdb/build/release/test/unittest --test-dir . "[postgres_scanner]"
        ./build/release/concurrency_test

    - uses: actions/upload-artifact@v2
      with:
        name: postgres-scanner
        path: |
          build/release/postgres_scanner.duckdb_extension